[*]

; Set Chat Template
jinja = true

; GPU Performance
n-gpu-layers = -1
flash-attn = on
fit = off

; Overall Performance
prio = 3
prio-batch = 3

; Increased Batch Size
batch-size = 2048
ubatch-size = 1024

; Set reasonable max thinking budgets
reasoning-budget-message = '... Taking too long, need to answer.'

[ggml-org/Qwen3-ASR-1.7B-GGUF:Q8_0]

; Alias
alias = Qwen3-ASR

; Model Name
hf = ggml-org/Qwen3-ASR-1.7B-GGUF:Q8_0

; Context Size
ctx-size = 896
parallel = 1
cache-ram = 0

; Model Load Behavior
load-on-startup = true
